//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBears
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_InvestmentTrack
    {
        public Nullable<int> id { get; set; }
        public Nullable<decimal> Investment { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> CountedDays { get; set; }
        public Nullable<double> RI { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Next_Date { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string Descid { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<int> IncomeFrom { get; set; }
        public int sno { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Valid_date { get; set; }
        public Nullable<int> Counted { get; set; }
        public Nullable<decimal> WishAmt { get; set; }
        public Nullable<int> wish_count { get; set; }
        public Nullable<System.DateTime> validdate_old { get; set; }
        public Nullable<int> NewDaysTemp { get; set; }
        public Nullable<int> NewTempTotDays { get; set; }
        public Nullable<int> RealCountedDays { get; set; }
        public Nullable<int> last_cuter { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
        public Nullable<decimal> ExtraIncome { get; set; }
        public Nullable<decimal> ExtraRoi { get; set; }
    }
}
